### ISSUE TITLE
Hi, is the cmakelist in the top-level dir missing?

### ISSUE THREAD

**Issue by DerThorsten** [ycollet/coinor-cmake#1]
Hi, is the cmakelist in the top-level dir missing?

**Comment by ycollet** [comment]
You need to copy all the content from the Cbc directory (in this repo) to the directory of Cbc download from the coinor website.
From example:
wget http://www.coin-or.org/download/source/Cbc/Cbc-2.9.6.tgz
tar xvfz Cbc-2.9.6.tgz
git clone git@github.com:ycollet/coinor-cmake.git
cd coinor-cmake/Cbc
cp -r \* ../../Cbc-2.9.6
cd ../../Cbc-2.9.6
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
make 
....
