### ISSUE TITLE
when ipopt project will be supported?

### ISSUE THREAD

**Issue by frenet** [ycollet/coinor-cmake#2]
when ipopt project will be supported in cmake?
I'm looking forward to them.

**Comment by ycollet** [comment]
OK, I will try to have a look asap. Maybe next week.
Up to know, I focused on the Cbc / Clp / Symphony things. But I think it's time to move forward with ipopt :)

Best regards,

Yc

----- Mail original -----
De: "Dunjiang Song" notifications@github.com
À: "ycollet/coinor-cmake" coinor-cmake@noreply.github.com
Envoyé: Mercredi 30 Septembre 2015 05:52:19
Objet: [coinor-cmake] when ipopt project will be supported? (#2)

when ipopt project will be supported in cmake? 
I'm looking forward to them.

**Comment by frenet** [comment]
Thank you very much, more and more people are now paying attentions to cmake.

**Comment by ycollet** [comment]
Yes, I totally agree with this. With cmake, it's now possible to compile something "easily" on windows :)

----- Mail original -----
De: "Dunjiang Song" notifications@github.com
À: "ycollet/coinor-cmake" coinor-cmake@noreply.github.com
Cc: "ycollet" ycollette.nospam@free.fr
Envoyé: Mercredi 30 Septembre 2015 15:20:33
Objet: Re: [coinor-cmake] when ipopt project will be supported? (#2)

Thank you very much, more and more people are now paying attentions to cmake.

**Comment by ycollet** [comment]
I made some progresses in the compilation of ipopt.
I still have some problems with the examples. coinhsl is still mandatory to allow ipopt to work with the examples. I tested with only mumps, but I still have some difficulties with mumps is the only solver activated.

The windows compilation has still not been tested. I will try mingw soon (I have no intel fortran compiler under windows).
