### ISSUE TITLE
ipopt cmake can not find DL_INCLUDE_DIR and DL_LIBRARY on Windows

### ISSUE THREAD

**Issue by econwang** [ycollet/coinor-cmake#3]
The Fortran compiler identification is Intel 17.0.4.20170411
CMake Warning (dev) at C:/cmake/share/cmake-3.9/Modules/FortranCInterface.cmake:295 (message):
  No FortranCInterface mangling known for mymod:my_sub
Call Stack (most recent call first):
  CMakeLists.txt:283 (FortranCInterface_HEADER)
This warning is for project developers.  Use -Wno-dev to suppress it.

Checking whether system has ANSI C header files
ANSI C header files - not found
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find DL (missing: DL_LIBRARY DL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindDL.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:627 (find_package)

Configuring incomplete, errors occurred!
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeOutput.log".
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeError.log".

**Comment by ycollet** [comment]
Thanks for the report.

I see two problems:
- the first one: libdl.so or the headers related to libdl.so are not installed. You need to install the package which provides dlfcn.h if your are starting cmake under a mingw or cygwin shell under Windows.
- the second one: the FortranCInterface macro is not able to find how a Fortran symbol is made using the Intel Fortran compiler. For this one, I will have a look ASAP. I have now access to a fortran compiler, so, I will check this one my side.

Best regards,

----- Mail original -----
De: "Stephen Y.F. Wang" <notifications@github.com>
À: "ycollet/coinor-cmake" <coinor-cmake@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Jeudi 17 Août 2017 14:11:56
Objet: [ycollet/coinor-cmake] ipopt cmake can do find DL_INCLUDE_DIR and DL_LIBRARY on Windows (#3)



The Fortran compiler identification is Intel 17.0.4.20170411 
CMake Warning (dev) at C:/cmake/share/cmake-3.9/Modules/FortranCInterface.cmake:295 (message): 
No FortranCInterface mangling known for mymod:my_sub 
Call Stack (most recent call first): 
CMakeLists.txt:283 (FortranCInterface_HEADER) 
This warning is for project developers. Use -Wno-dev to suppress it. 

Checking whether system has ANSI C header files 
ANSI C header files - not found 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message): 
Could NOT find DL (missing: DL_LIBRARY DL_INCLUDE_DIR) 
Call Stack (most recent call first): 
C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE) 
cmake/FindDL.cmake:23 (find_package_handle_standard_args) 
CMakeLists.txt:627 (find_package) 

Configuring incomplete, errors occurred! 
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeOutput.log". 
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeError.log".

**Comment by ycollet** [comment]
To compile under windows with the Intel compilers, I use the following command line:
- I first open a "Intel compiler command prompt".
- then, I go to the build directory and I enter this command line (the path to the intel compiler is to be updated":
```
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=c:/coin-bin -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe" -DCMAKE_Fortran_COMPILER:FILEPATH="C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/ifort.exe" -G "NMake Makefiles" ..
```
- then I just to a "nmake" to compile the project.

**Comment by econwang** [comment]
I actually use the same command under "Intel compiler command prompt", without cygwin installed, but produce the above error, the full output is:
`-- The C compiler identification is Intel 17.0.4.20170411
-- The CXX compiler identification is Intel 17.0.4.20170411
-- Check for working C compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe
-- Check for working C compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Anaconda2/python.exe (found version "2.7.13")
-- The Fortran compiler identification is Intel 17.0.4.20170411
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL but not MODULE mangling
CMake Warning (dev) at C:/cmake/share/cmake-3.9/Modules/FortranCInterface.cmake:295 (message):
  No FortranCInterface mangling known for mymod:my_sub
Call Stack (most recent call first):
  CMakeLists.txt:283 (FortranCInterface_HEADER)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for bzlib.h
-- Looking for bzlib.h - not found
-- Looking for ctype.h
-- Looking for ctype.h - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for endian.h
-- Looking for endian.h - not found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for ieeefp.h
-- Looking for ieeefp.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for readline/readline.h
-- Looking for readline/readline.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for stdarg.h
-- Looking for stdarg.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for windows.h
-- Looking for windows.h - found
-- Looking for zlib.h
-- Looking for zlib.h - not found
-- Looking for C++ include cctype
-- Looking for C++ include cctype - found
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Looking for C++ include cieeefp
-- Looking for C++ include cieeefp - not found
-- Looking for C++ include cfloat
-- Looking for C++ include cfloat - found
-- Looking for C++ include cinttypes
-- Looking for C++ include cinttypes - found
-- Looking for C++ include cassert
-- Looking for C++ include cassert - found
-- Looking for C++ include cstdio
-- Looking for C++ include cstdio - found
-- Looking for C++ include cstdlib
-- Looking for C++ include cstdlib - found
-- Looking for C++ include cstdarg
-- Looking for C++ include cstdarg - found
-- Looking for C++ include cstddef
-- Looking for C++ include cstddef - found
-- Looking for C++ include cstring
-- Looking for C++ include cstring - found
-- Looking for C++ include ctime
-- Looking for C++ include ctime - found
-- Performing Test HAVE_QUNUSED_ARGUMENTS
-- Performing Test HAVE_QUNUSED_ARGUMENTS - Failed
-- Check size of int *
-- Check size of int * - done
-- Looking for isfinite
-- Looking for isfinite - not found
-- Looking for dran48
-- Looking for dran48 - not found
-- Looking for rand
-- Looking for rand - found
-- Looking for snprintf
-- Looking for snprintf - not found
-- Looking for std::rand
-- Looking for std::rand - not found
-- Looking for va_copy
-- Looking for va_copy - not found
-- Looking for vsnprintf
-- Looking for vsnprintf - not found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Checking whether system has ANSI C header files
-- Looking for 8 include files dlfcn.h, ..., float.h
-- Looking for 8 include files dlfcn.h, ..., float.h - not found
-- ANSI C header files - not found
-- Looking for DIR in sys/stat.h;sys/types.h;dirent.h
-- Looking for DIR in sys/stat.h;sys/types.h;dirent.h - not found.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error at C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find DL (missing: DL_LIBRARY DL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindDL.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:627 (find_package)


-- Configuring incomplete, errors occurred!
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeOutput.log".
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeError.log".`

**Comment by ycollet** [comment]
OK, I see.
In the main CMakeLists.txt file, line 627, replace "find_package(DL REQUIRED)" by "find_package(DL)".

----- Mail original -----
De: "Stephen Y.F. Wang" <notifications@github.com>
À: "ycollet/coinor-cmake" <coinor-cmake@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Vendredi 18 Août 2017 13:41:19
Objet: Re: [ycollet/coinor-cmake] ipopt cmake can not find DL_INCLUDE_DIR and DL_LIBRARY on Windows (#3)



I actually use the same command under "Intel compiler command prompt", without cygwin installed, but produce the above error, the full output is: 
`-- The C compiler identification is Intel 17.0.4.20170411 
-- The CXX compiler identification is Intel 17.0.4.20170411 
-- Check for working C compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe 
-- Check for working C compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe -- works 
-- Detecting C compiler ABI info 
-- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done 
-- Check for working CXX compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe 
-- Check for working CXX compiler: C:/Program Files (x86)/IntelSWTools/parallel_studio_xe_2017/compilers_and_libraries_2017/windows/bin/intel64/icl.exe -- works 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Detecting CXX compile features 
-- Detecting CXX compile features - done 
-- Found PythonInterp: C:/Anaconda2/python.exe (found version "2.7.13") 
-- The Fortran compiler identification is Intel 17.0.4.20170411 
-- Detecting Fortran/C Interface 
-- Detecting Fortran/C Interface - Found GLOBAL but not MODULE mangling 
CMake Warning (dev) at C:/cmake/share/cmake-3.9/Modules/FortranCInterface.cmake:295 (message): 
No FortranCInterface mangling known for mymod:my_sub 
Call Stack (most recent call first): 
CMakeLists.txt:283 (FortranCInterface_HEADER) 
This warning is for project developers. Use -Wno-dev to suppress it. 

-- Looking for assert.h 
-- Looking for assert.h - found 
-- Looking for bzlib.h 
-- Looking for bzlib.h - not found 
-- Looking for ctype.h 
-- Looking for ctype.h - found 
-- Looking for dlfcn.h 
-- Looking for dlfcn.h - not found 
-- Looking for endian.h 
-- Looking for endian.h - not found 
-- Looking for float.h 
-- Looking for float.h - found 
-- Looking for ieeefp.h 
-- Looking for ieeefp.h - not found 
-- Looking for inttypes.h 
-- Looking for inttypes.h - found 
-- Looking for math.h 
-- Looking for math.h - found 
-- Looking for memory.h 
-- Looking for memory.h - found 
-- Looking for readline/readline.h 
-- Looking for readline/readline.h - not found 
-- Looking for stdint.h 
-- Looking for stdint.h - found 
-- Looking for stdlib.h 
-- Looking for stdlib.h - found 
-- Looking for stdio.h 
-- Looking for stdio.h - found 
-- Looking for stdarg.h 
-- Looking for stdarg.h - found 
-- Looking for stddef.h 
-- Looking for stddef.h - found 
-- Looking for strings.h 
-- Looking for strings.h - not found 
-- Looking for string.h 
-- Looking for string.h - found 
-- Looking for sys/stat.h 
-- Looking for sys/stat.h - found 
-- Looking for sys/types.h 
-- Looking for sys/types.h - found 
-- Looking for time.h 
-- Looking for time.h - found 
-- Looking for unistd.h 
-- Looking for unistd.h - not found 
-- Looking for windows.h 
-- Looking for windows.h - found 
-- Looking for zlib.h 
-- Looking for zlib.h - not found 
-- Looking for C++ include cctype 
-- Looking for C++ include cctype - found 
-- Looking for C++ include cmath 
-- Looking for C++ include cmath - found 
-- Looking for C++ include cieeefp 
-- Looking for C++ include cieeefp - not found 
-- Looking for C++ include cfloat 
-- Looking for C++ include cfloat - found 
-- Looking for C++ include cinttypes 
-- Looking for C++ include cinttypes - found 
-- Looking for C++ include cassert 
-- Looking for C++ include cassert - found 
-- Looking for C++ include cstdio 
-- Looking for C++ include cstdio - found 
-- Looking for C++ include cstdlib 
-- Looking for C++ include cstdlib - found 
-- Looking for C++ include cstdarg 
-- Looking for C++ include cstdarg - found 
-- Looking for C++ include cstddef 
-- Looking for C++ include cstddef - found 
-- Looking for C++ include cstring 
-- Looking for C++ include cstring - found 
-- Looking for C++ include ctime 
-- Looking for C++ include ctime - found 
-- Performing Test HAVE_QUNUSED_ARGUMENTS 
-- Performing Test HAVE_QUNUSED_ARGUMENTS - Failed 
-- Check size of int * 
-- Check size of int * - done 
-- Looking for isfinite 
-- Looking for isfinite - not found 
-- Looking for dran48 
-- Looking for dran48 - not found 
-- Looking for rand 
-- Looking for rand - found 
-- Looking for snprintf 
-- Looking for snprintf - not found 
-- Looking for std::rand 
-- Looking for std::rand - not found 
-- Looking for va_copy 
-- Looking for va_copy - not found 
-- Looking for vsnprintf 
-- Looking for vsnprintf - not found 
-- Looking for _snprintf 
-- Looking for _snprintf - not found 
-- Looking for _vsnprintf 
-- Looking for _vsnprintf - not found 
-- Checking whether system has ANSI C header files 
-- Looking for 8 include files dlfcn.h, ..., float.h 
-- Looking for 8 include files dlfcn.h, ..., float.h - not found 
-- ANSI C header files - not found 
-- Looking for DIR in sys/stat.h;sys/types.h;dirent.h 
-- Looking for DIR in sys/stat.h;sys/types.h;dirent.h - not found. 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message): 
Could NOT find DL (missing: DL_LIBRARY DL_INCLUDE_DIR) 
Call Stack (most recent call first): 
C:/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE) 
cmake/FindDL.cmake:23 (find_package_handle_standard_args) 
CMakeLists.txt:627 (find_package) 

-- Configuring incomplete, errors occurred! 
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeOutput.log". 
See also "F:/SLib/Intel/Ipopt-3.12.8/build/CMakeFiles/CMakeError.log".`

**Comment by econwang** [comment]
Thanks, I finally get the `libipopt` with MKL by turn on `COIN_HAS_MKL`, it works, an issue is that turn on `COIN_HAS_MKL` does not automatically turn on `COIN_HAS_LAPACK`.

**Comment by ycollet** [comment]
Thanks for this comment. I will fix this soon !
