### ISSUE TITLE
Building CLP from svn revision 2333 fails to link

### ISSUE THREAD

**Issue by coroa** [ycollet/coinor-cmake#5]
Hi there, thanks for that new build suite.

Building CLP from current svn fails with:

```
[ 98%] Linking CXX executable ../bin/clp
../bin/libClp.a(ClpSolve.cpp.o): In function `ClpSimplex::initialSolve(ClpSolve&)':
ClpSolve.cpp:(.text+0x13351): undefined reference to `ClpCholeskyMumps::ClpCholeskyMumps(int)'
ClpSolve.cpp:(.text+0x14905): undefined reference to `ClpCholeskyMumps::ClpCholeskyMumps(int)'
collect2: error: ld returned 1 exit status
Clp/CMakeFiles/clp.dir/build.make:97: recipe for target 'bin/clp' failed
make[2]: *** [bin/clp] Error 1
CMakeFiles/Makefile2:1223: recipe for target 'Clp/CMakeFiles/clp.dir/all' failed
make[1]: *** [Clp/CMakeFiles/clp.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
```

As options, I had to select USE_BZLIB, USE_ZLIB and USE_LAPACK. USE_MUMPS or/and ENABLE_DOWNLOAD_MUMPS do not affect the linking error.

And an unrelated question: I'm trying to use the cmake project to get CLP to use CHOLMOD and AMD from suitesparse. Does that work yet?

Thanks,
Jonas

**Comment by ycollet** [comment]
Can you try this last version ?

Normally, SuiteSparse works fine with Cbc / Clp. But I will check ASAP.

**Comment by ycollet** [comment]
I tested the build of Cbc because Clp has no revision 2333 ...

**Comment by coroa** [comment]
Strange it seems to work now. Sorry for the noise!

**Comment by ycollet** [comment]
No problem, I found a problem with lapack management and mumps and with bzip2 (www.bzip.org is dead ...) :)
